### ISSUE TITLE
Ezra - please change version numbers (Actually please remove Ezra from your repo for now)

### ISSUE THREAD

**Issue by Ezra-Hubbard** [techecoyote/LooNaticsAsylum#12]
I don't know why you have changed the version numbers but this will completely mess anyone up who uses the official Ezra repo.

If people have your repo and the official Ezra repo installed they will not get any official updates because you have changed all the version numbers.

I'm absolutely fine with you hosting Ezra in your repo but please use the correct versioning. Having two sets of version numbers will be a complete mess.

Cheers

Official Ezra repo btw is ezra-hubbard.github.io

**Comment by Ezra-Hubbard** [comment]
For now I would recommend people don't install Ezra from this repo as it will break your ability to get actual updates of ezra

**Comment by Ezra-Hubbard** [comment]
Worse, you have changed my accounts module so that will break the setup of people who install Ezra from official source.

Why would you even do that?

**Comment by techecoyote** [comment]
Sorry to get back to you so late. Don't read my Email too often.
I apologize for hijacking EZRA. I did not realize it was still being maintained.
I was asked by many users to include it in my repo so assumed it was gone.
I change my version numbers according to the date I upload to the repo.
I also changed myaccounts to youraccounts because I didn't want it to
interfere with other(s) versions from other repos even though it's dead now.

Again, I apologize for my mistake. Wasn't trying to walk all over you or Ezra addon.
Since then, I have removed Ezra. I wrote an apology in the new addon ADINA
hoping you would see it & forgive my mistake...

Feel free to contact me any time you wish...
Thank you for your time

Here is a link to my TG group...
THE WAREHOUSE

https://t.me/+BKQ7ntWeJoFjMjVh
________________________________
