### ISSUE TITLE
Loonatics  Empire. 

### ISSUE THREAD

**Issue by Greg0580** [techecoyote/LooNaticsAsylum#5]
Since kodi been updated to kodi 19.3. Loonatics Empire  video  addon won't install  it kicks you out of kodi.  And since the Scraper  has been updated from 1.5.7 you can't Scraper  any movies or TV shows  the Scraper starts and quickly comes up no streams . And swift tv is down when you try to use it shows error message.

**Comment by agemp** [comment]
was a great addon but now having the same problem!

**Comment by kevwag** [comment]
Similar problem here. The problem is occurring because LE uses someone else's scraper module (fenom scrapers) but LE hasn't been kept up-to-date so as to work with the latest version of the scraper module (currently v2.0.5). LE currently only works with v1.5.7.
If you have other addons that use Fenom scrapers (ie: Venom), then it's likely that the scraper has been updated.

There is a clumsy workaround: open the info page for the scraper module, click "versions", then select version 1.5.7 from the LE repo and vice-versa to switch back when you want to use the other addon(s). It's far from ideal but there's not much else we can do until such time LE gets updated. 

It's a cautionary tale for devs - If you're using someone else's modules in your software in order to cut corners and minimise the work you have to put in yourself, you should FORK the module and give it a new unique identity. That way the original devs of the module can continue to update it without the changes breaking your addon. You can always re-fork the updated versions as and when you have time to check that your code works with the updates ;)

**Comment by kevwag** [comment]
> Yes that's correct about Fenom scraper. And you can not install Loonatics Empire from video addon on 19.3 matrix. You have install kodi 19.1 install it from there then install 19.3 . Course if you try install Loonatics Empire on 19.3 it kicks you out of kodi to the home page.
I have installed LE on 19.3 Matrix without any problems. I've also Installed it on 20.0 Nexus Beta, also with no problems (apart from the scraper issue we've already covered.)

TBH, I only really wanted LE because it has the lists for documentaries and stand-up comedy - nice to have but ultimately, not essential, probably even useless before too long if it's not kept maintained.  If the associated IPTV addons were better written and supported integration into the Kodi EPG then I would be far keener to see this addon get fixed. As that is not the case, I'm not going to lose any sleep over uninstalling it.

My Recommendation to anyone still struggling with LE would be to just uninstall it and replace it with the latest version of Venom. It's more stable, faster, updated regularly and since the same team also make the Fenom scrapers, you'll never find yourself stuck with an addon that's no longer compatible with its own scrapers! LE was more than likely forked from Venom in the first place!
